import type { EditorColorGenerator } from "../../types/editorColors";
import { opacity } from "../opacity";

export const editor: EditorColorGenerator = (palette) => {
  return {
    editor: {
      background: palette.bgMain,
      findMatchBackground: `${palette.red}${opacity.opacityLow}`,
      findMatchBorder: `${palette.red}${opacity.opacityHigh}`,
      findMatchHighlightBackground: `${palette.red}${opacity.opacityLow}`,
      findMatchHighlightBorder: `${palette.red}${opacity.opacityHigh}`,
      findRangeHighlightBackground: `${palette.red}${opacity.opacityLow}`,
      focusedStackFrameHighlightBackground: `${palette.red}${opacity.opacityLow}`,
      foreground: palette.fgMain,
      hoverHighlightBackground: `${palette.fgShadow}${opacity.opacityLow}`,
      inlineValuesBackground: `${palette.cyan}${opacity.opacityLow}`,
      inlineValuesForeground: palette.fgMain,
      lineHighlightBorder: "#00000000",
      lineHighlightBackground: `${palette.bgLight}${opacity.opacityLow}`,
      linkedEditingBackground: `${palette.orange}${opacity.opacityLow}`,
      rangeHighlightBackground: `${palette.fgShadow}${opacity.opacityLow}`,
      selectionBackground: `${palette.fgShadow}${opacity.opacityHigh}`,
      selectionHighlightBorder: `${palette.fgShadow}${opacity.opacityHigh}`,
      snippetFinalTabstopHighlightBorder: palette.bgLight,
      snippetTabstopHighlightBackground: palette.bgLight,
      stackFrameHighlightBackground: `${palette.fgShadow}${opacity.opacityLow}`,
      wordHighlightBackground: `${palette.fgShadow}${opacity.opacityLow}`,
      wordHighlightStrongBackground: `${palette.fgShadow}${opacity.opacityLow}`,
    },
    editorBracketHighlight: {
      foreground1: palette.cyan,
      foreground2: palette.blue,
      foreground3: palette.green,
      unexpectedBracket: {
        foreground: palette.orange,
      },
    },
    editorBracketMatch: {
      background: `${palette.fgShadow}${opacity.opacityLow}`,
      border: palette.fgShadow,
    },
    editorBracketPairGuide: {
      activeBackground1: "#00000000",
      activeBackground2: "#00000000",
      activeBackground3: "#00000000",
      activeBackground4: "#00000000",
      activeBackground5: "#00000000",
      activeBackground6: "#00000000",
      background1: "#00000000",
      background2: "#00000000",
      background3: "#00000000",
      background4: "#00000000",
      background5: "#00000000",
      background6: "#00000000",
    },
    editorCodeLens: { foreground: palette.fgShadow },
    editorCursor: { foreground: palette.fgSub },
    editorError: { foreground: palette.orange },
    editorGhostText: { foreground: palette.fgShadow },
    editorGroup: {
      border: palette.bgDarker,
      dropBackground: `${palette.bgDarker}${opacity.opacityLow}`,
    },
    editorGroupHeader: { tabsBackground: palette.bgDark },
    editorGutter: {
      addedBackground: palette.green,
      modifiedBackground: palette.blue,
    },
    editorHint: { foreground: palette.fgShadow },
    editorInfo: { foreground: palette.purple },
    editorLightBulb: { foreground: palette.yellow },
    editorLightBulbAutoFix: { foreground: palette.cyan },
    editorLineNumber: {
      activeForeground: palette.fgSub,
      foreground: palette.fgShadow,
    },
    editorLink: { activeForeground: palette.blue },
    editorOverviewRuler: {
      border: palette.bgDark,
      bracketMatchForeground: palette.fgShadow,
      errorForeground: `${palette.orange}${opacity.opacityHigh}`,
      findMatchForeground: `${palette.red}${opacity.opacityHigh}`,
      rangeHighlightForeground: `${palette.fgShadow}${opacity.opacityHigh}`,
      selectionHighlightForeground: `${palette.fgShadow}${opacity.opacityHigh}`,
      wordHighlightForeground: `${palette.fgShadow}${opacity.opacityHigh}`,
      wordHighlightStrongForeground: `${palette.fgShadow}${opacity.opacityHigh}`,
    },
    editorPane: { background: palette.bgDark },
    editorRuler: { foreground: palette.fgShadow },
    editorStickyScrollHover: { background: palette.bgDarker },
    editorUnicodeHighlight: {
      background: `${palette.yellow}${opacity.opacityLow}`,
      border: palette.yellow,
    },
    editorUnnecessaryCode: { opacity: `#000000${opacity.opacityHigh}` },
    editorWarning: { foreground: palette.yellow },
    editorWhitespace: { foreground: `${palette.purple}${opacity.opacityLow}` },
    editorWidget: { background: palette.bgLight, border: palette.bgDark },
  };
};
